- id: dataform-compile
  name: Dataform compile
  entry: hooks/dataform-compile.sh
  files: (\.sqlx|\.js)$
  language: script
  pass_filenames: false

- id: dataform-format
  name: Dataform format
  entry: hooks/dataform-format.sh
  files: (\.sqlx|\.js)$
  language: script
  pass_filenames: true

- id: dataform-sqlfluff-lint
  name: Dataform sqlfluff lint
  entry: dataform-sqlfluff-lint
  files: (\.sqlx|\.js)$
  language: python
  pass_filenames: true

- id: dataform-syntax-check
  name: Dataform syntax check
  entry: dataform-syntax-check
  files: (\.sqlx|\.js)$
  language: python
  pass_filenames: true
